# Generated by Django 2.0.1 on 2018-01-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareLottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='彩票名字')),
                ('trem', models.CharField(max_length=20, verbose_name='期')),
                ('time', models.TimeField(verbose_name='开奖时间')),
                ('sale', models.BigIntegerField(verbose_name='全国销量')),
                ('pool', models.BigIntegerField(verbose_name='奖池奖金')),
                ('matchboll', models.CharField(max_length=50, verbose_name='开奖号码')),
                ('bonus', models.CharField(max_length=100, verbose_name='开奖信息')),
            ],
        ),
    ]
