# Generated by Django 2.0.1 on 2018-01-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WelfareLottery', '0002_auto_20180116_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welfarelottery',
            name='time',
            field=models.CharField(max_length=30, verbose_name='开奖时间'),
        ),
    ]
